[2025-03-05T22:39:48.833+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-05T22:39:48.840+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: forecast_stock_price.train_model manual__2025-03-05T22:39:47.428444+00:00 [queued]>
[2025-03-05T22:39:48.842+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: forecast_stock_price.train_model manual__2025-03-05T22:39:47.428444+00:00 [queued]>
[2025-03-05T22:39:48.843+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-03-05T22:39:48.846+0000] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): train_model> on 2025-03-05 22:39:47.428444+00:00
[2025-03-05T22:39:48.854+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'forecast_stock_price', 'train_model', 'manual__2025-03-05T22:39:47.428444+00:00', '--job-id', '62', '--raw', '--subdir', 'DAGS_FOLDER/forecast_stock_price.py', '--cfg-path', '/tmp/tmp_1dh_b9_']
[2025-03-05T22:39:48.855+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=506) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-05T22:39:48.856+0000] {standard_task_runner.py:105} INFO - Job 62: Subtask train_model
[2025-03-05T22:39:48.856+0000] {standard_task_runner.py:72} INFO - Started process 509 to run task
[2025-03-05T22:39:48.897+0000] {task_command.py:467} INFO - Running <TaskInstance: forecast_stock_price.train_model manual__2025-03-05T22:39:47.428444+00:00 [running]> on host d0b2b24d510a
[2025-03-05T22:39:48.944+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='forecast_stock_price' AIRFLOW_CTX_TASK_ID='train_model' AIRFLOW_CTX_EXECUTION_DATE='2025-03-05T22:39:47.428444+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-05T22:39:47.428444+00:00'
[2025-03-05T22:39:48.945+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-05T22:39:48.947+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-6.10.14-linuxkit-aarch64-with-glibc2.36
[2025-03-05T22:39:48.947+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-03-05T22:39:48.947+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-03-05T22:39:49.622+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-03-05T22:41:16.768+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-03-05T22:41:18.502+0000] {cursor.py:1156} INFO - Number of results in first chunk: 14
[2025-03-05T22:41:18.504+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-05T22:41:18.532+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-05T22:41:18.533+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=forecast_stock_price, task_id=train_model, run_id=manual__2025-03-05T22:39:47.428444+00:00, execution_date=20250305T223947, start_date=20250305T223948, end_date=20250305T224118
[2025-03-05T22:41:18.565+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-05T22:41:18.582+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-05T22:41:18.583+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
